### PR TITLE
Implement a new console

### LINKED ISSUE #55: SQL Console should support multi-line statements
Currently the console executes the input when enter is hit. Normal behavior for a SQL console is to accept multi-line statements terminated with a semicolon.

### PR DESCRIPTION
**Pull request by mgxm**
I've added a new console that own support to
- multi-line statements
- commands
- history

Close #55

### CODE REVIEW

**Comment by andygrove** [comment]
Hey, this looks awesome. Thanks for contributing!

I tried building from your branch but get this error:

```
  = note: /usr/bin/ld: cannot find -lncursesw
          collect2: error: ld returned 1 exit status
```

So this change brings in a dependency on a library. Is this library available on all platforms? Is there a way we could do this without introducing non-Rust dependencies.

I'd like to keep the project as pure Rust code that can be built easily with `cargo build` if possible.

**Comment by mgxm** [comment]
Sure, no problem.
I've looked at other crates and it looks like they're all inactive.
I tried to find for one that is more active and forgot to look at the dependencies.
I'll make the modifications

**Comment by andygrove** [comment]
Thanks! This works very nicely.

Just one last thing - I guess it was undocumented but it should be possible to terminate the console session by typing "quit" or "exit" without a semicolon in this case ... will that be easy to add? After that I can merge this.

**Comment by andygrove** [comment]
Awesome! Thanks again for contributing.

**Pull request merged**
