### PR TITLE
ARROW-4493: make accumulate_scalar somewhat exhaustive and easier to read

### PR DESCRIPTION
**Pull request by tupshin**
I went digging into the code to see about implementing COUNT() and got sidetracked by related code. 
There is room for further refactor later to make this function never panic, but in the meantime, I think that calling out each case that can fail makes it much easier to understand and easier to avoid a runtime error from non-exhaustiveness

### CODE REVIEW

**Comment by andygrove** [comment]
This looks great, thank you. DataFusion was just recently donated to Apache Arrow, so do you think you could create a JIRA and PR there instead?

Please see the README here for info on the process for contributing: 

https://github.com/apache/arrow

**Comment by tupshin** [comment]
Thanks. Issue created and title of pull request changed to match. I'm pretty motivated to make some more substantial contributions to this project, so I'll be looking for issues that I can be mentored through as I explore further.

**Comment by andygrove** [comment]
Hi @tupshin .. Sorry, you will need to fork the apache arrow repo and create this PR against that one.

**Comment by kujon** [comment]
@andygrove would be really nice to flag this repo as archived.

**Comment by tupshin** [comment]
got it and done. thanks

**Pull request closed without merging**
